# Generated by Django 6.1.1 on 2026-09-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adds", "0002_postimage"),
    ]

    operations = [
        migrations.DeleteModel(name="PostImage"),
    ]
